language: java
notifications:
  email:
    recipients:
      - epierrej@uh.edu.com
      - aravishankar2@uh.edu.com
<<<<<<< HEAD
      - qdinh2@uh.edu
=======
      - qdinh2@uh.edu
>>>>>>> origin/master
