language: java
notifications:
  email:
    recipients:
      - epierrej@uh.edu.com
      - aravishankar2@uh.edu.com
      - qdinh2@uh.edu
<<<<<<< HEAD
script: mvn test -B
=======
script: mvn test -B
>>>>>>> 9449c374da007bf0b2f000c20f6712d694c6501b
